In [171]:
from pymongo import MongoClient
import pandas as pd
from datetime import datetime

In [172]:
client = MongoClient("mongodb://root:rootpass@localhost:27017")
print(client.server_info()['version'])

8.2.6

In [173]:
db = client['Veterinaria']
colecao = db['donos']

In [174]:
dados = [
{"tutor":"Ana","animal":"Cachorro","nome_pet":"Rex1","servico":"Consulta","valor":120,"cidade":"Assis","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Bruno","animal":"Gato","nome_pet":"Mimi2","servico":"Vacinação","valor":95,"cidade":"Assis","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
{"tutor":"Carlos","animal":"Cachorro","nome_pet":"Thor3","servico":"Banho","valor":60,"cidade":"Assis","data":datetime(2026,3,3),"forma_pagamento":"Dinheiro"},
{"tutor":"Daniela","animal":"Ave","nome_pet":"Piu4","servico":"Exame","valor":180,"cidade":"Assis","data":datetime(2026,3,4),"forma_pagamento":"Cartão"},
{"tutor":"Eduardo","animal":"Gato","nome_pet":"Luna5","servico":"Consulta","valor":130,"cidade":"Assis","data":datetime(2026,3,5),"forma_pagamento":"Pix"},
{"tutor":"Fernanda","animal":"Cachorro","nome_pet":"Bob6","servico":"Vacinação","valor":90,"cidade":"Assis","data":datetime(2026,3,6),"forma_pagamento":"Dinheiro"},
{"tutor":"Gabriel","animal":"Coelho","nome_pet":"Pompom7","servico":"Consulta","valor":110,"cidade":"Assis","data":datetime(2026,3,7),"forma_pagamento":"Pix"},
{"tutor":"Helena","animal":"Cachorro","nome_pet":"Mel8","servico":"Cirurgia","valor":820,"cidade":"Assis","data":datetime(2026,3,8),"forma_pagamento":"Cartão"},
{"tutor":"Igor","animal":"Gato","nome_pet":"Simba9","servico":"Banho","valor":55,"cidade":"Assis","data":datetime(2026,3,9),"forma_pagamento":"Cartão"},
{"tutor":"Juliana","animal":"Cachorro","nome_pet":"Nina10","servico":"Consulta","valor":125,"cidade":"Assis","data":datetime(2026,3,10),"forma_pagamento":"Pix"},
{"tutor":"Lucas","animal":"Ave","nome_pet":"Sky11","servico":"Exame","valor":200,"cidade":"Assis","data":datetime(2026,3,11),"forma_pagamento":"Cartão"},
{"tutor":"Mariana","animal":"Gato","nome_pet":"Lili12","servico":"Consulta","valor":135,"cidade":"Assis","data":datetime(2026,3,12),"forma_pagamento":"Pix"},
{"tutor":"Nicolas","animal":"Cachorro","nome_pet":"Bolt13","servico":"Vacinação","valor":100,"cidade":"Assis","data":datetime(2026,3,13),"forma_pagamento":"Dinheiro"},
{"tutor":"Patricia","animal":"Cachorro","nome_pet":"Max14","servico":"Consulta","valor":140,"cidade":"Ourinhos","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Rafael","animal":"Gato","nome_pet":"Mia15","servico":"Banho","valor":65,"cidade":"Ourinhos","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
{"tutor":"Sofia","animal":"Cachorro","nome_pet":"Luna16","servico":"Cirurgia","valor":900,"cidade":"Ourinhos","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
{"tutor":"Thiago","animal":"Ave","nome_pet":"Blue17","servico":"Exame","valor":170,"cidade":"Ourinhos","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
{"tutor":"Vanessa","animal":"Gato","nome_pet":"Nino18","servico":"Consulta","valor":125,"cidade":"Ourinhos","data":datetime(2026,3,5),"forma_pagamento":"Dinheiro"},
{"tutor":"William","animal":"Cachorro","nome_pet":"Thor19","servico":"Vacinação","valor":95,"cidade":"Ourinhos","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
{"tutor":"Beatriz","animal":"Coelho","nome_pet":"Fluffy20","servico":"Consulta","valor":115,"cidade":"Ourinhos","data":datetime(2026,3,7),"forma_pagamento":"Cartão"},
{"tutor":"Caio","animal":"Cachorro","nome_pet":"Spike21","servico":"Banho","valor":70,"cidade":"Ourinhos","data":datetime(2026,3,8),"forma_pagamento":"Dinheiro"},
{"tutor":"Diego","animal":"Gato","nome_pet":"Tom22","servico":"Consulta","valor":135,"cidade":"Ourinhos","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
{"tutor":"Elisa","animal":"Cachorro","nome_pet":"Mel23","servico":"Exame","valor":210,"cidade":"Ourinhos","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
{"tutor":"Felipe","animal":"Ave","nome_pet":"Kiwi24","servico":"Consulta","valor":120,"cidade":"Ourinhos","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
{"tutor":"Gisele","animal":"Gato","nome_pet":"Nina25","servico":"Vacinação","valor":85,"cidade":"Ourinhos","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
{"tutor":"Hugo","animal":"Cachorro","nome_pet":"Rex26","servico":"Consulta","valor":150,"cidade":"Ourinhos","data":datetime(2026,3,13),"forma_pagamento":"Cartão"},
{"tutor":"Iris","animal":"Cachorro","nome_pet":"Bob27","servico":"Consulta","valor":110,"cidade":"Pompeia","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Joao","animal":"Gato","nome_pet":"Luna28","servico":"Banho","valor":60,"cidade":"Pompeia","data":datetime(2026,3,2),"forma_pagamento":"Dinheiro"},
{"tutor":"Karen","animal":"Cachorro","nome_pet":"Thor29","servico":"Cirurgia","valor":780,"cidade":"Pompeia","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
{"tutor":"Leo","animal":"Ave","nome_pet":"Sky30","servico":"Exame","valor":160,"cidade":"Pompeia","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
{"tutor":"Marta","animal":"Gato","nome_pet":"Mimi31","servico":"Consulta","valor":120,"cidade":"Pompeia","data":datetime(2026,3,5),"forma_pagamento":"Cartão"},
{"tutor":"Nelson","animal":"Cachorro","nome_pet":"Max32","servico":"Vacinação","valor":90,"cidade":"Pompeia","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
{"tutor":"Olga","animal":"Coelho","nome_pet":"Pompom33","servico":"Consulta","valor":105,"cidade":"Pompeia","data":datetime(2026,3,7),"forma_pagamento":"Dinheiro"},
{"tutor":"Paulo","animal":"Cachorro","nome_pet":"Bolt34","servico":"Banho","valor":75,"cidade":"Pompeia","data":datetime(2026,3,8),"forma_pagamento":"Cartão"},
{"tutor":"Quezia","animal":"Gato","nome_pet":"Simba35","servico":"Consulta","valor":130,"cidade":"Pompeia","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
{"tutor":"Renato","animal":"Cachorro","nome_pet":"Nina36","servico":"Exame","valor":190,"cidade":"Pompeia","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
{"tutor":"Sara","animal":"Ave","nome_pet":"Blue37","servico":"Consulta","valor":115,"cidade":"Pompeia","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
{"tutor":"Tiago","animal":"Gato","nome_pet":"Lili38","servico":"Vacinação","valor":85,"cidade":"Pompeia","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
{"tutor":"Ursula","animal":"Cachorro","nome_pet":"Rex39","servico":"Consulta","valor":145,"cidade":"Marilia","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Vitor","animal":"Gato","nome_pet":"Mia40","servico":"Banho","valor":70,"cidade":"Marilia","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
{"tutor":"Wesley","animal":"Cachorro","nome_pet":"Thor41","servico":"Cirurgia","valor":870,"cidade":"Marilia","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
{"tutor":"Xuxa","animal":"Ave","nome_pet":"Piu42","servico":"Exame","valor":175,"cidade":"Marilia","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
{"tutor":"Yara","animal":"Gato","nome_pet":"Luna43","servico":"Consulta","valor":135,"cidade":"Marilia","data":datetime(2026,3,5),"forma_pagamento":"Dinheiro"},
{"tutor":"Zeca","animal":"Cachorro","nome_pet":"Bob44","servico":"Vacinação","valor":100,"cidade":"Marilia","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
{"tutor":"Aline","animal":"Coelho","nome_pet":"Fluffy45","servico":"Consulta","valor":120,"cidade":"Marilia","data":datetime(2026,3,7),"forma_pagamento":"Cartão"},
{"tutor":"Bruna","animal":"Cachorro","nome_pet":"Spike46","servico":"Banho","valor":80,"cidade":"Marilia","data":datetime(2026,3,8),"forma_pagamento":"Dinheiro"},
{"tutor":"Cesar","animal":"Gato","nome_pet":"Tom47","servico":"Consulta","valor":140,"cidade":"Marilia","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
{"tutor":"Dora","animal":"Cachorro","nome_pet":"Mel48","servico":"Exame","valor":220,"cidade":"Marilia","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
{"tutor":"Enzo","animal":"Ave","nome_pet":"Kiwi49","servico":"Consulta","valor":130,"cidade":"Marilia","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
{"tutor":"Fabio","animal":"Gato","nome_pet":"Nina50","servico":"Vacinação","valor":90,"cidade":"Marilia","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
]

In [175]:
colecao.insert_many(dados)

InsertManyResult([ObjectId('69c421dd055b4a41fe853b2d'), ObjectId('69c421dd055b4a41fe853b2e'), ObjectId('69c421dd055b4a41fe853b2f'), ObjectId('69c421dd055b4a41fe853b30'), ObjectId('69c421dd055b4a41fe853b31'), ObjectId('69c421dd055b4a41fe853b32'), ObjectId('69c421dd055b4a41fe853b33'), ObjectId('69c421dd055b4a41fe853b34'), ObjectId('69c421dd055b4a41fe853b35'), ObjectId('69c421dd055b4a41fe853b36'), ObjectId('69c421dd055b4a41fe853b37'), ObjectId('69c421dd055b4a41fe853b38'), ObjectId('69c421dd055b4a41fe853b39'), ObjectId('69c421dd055b4a41fe853b3a'), ObjectId('69c421dd055b4a41fe853b3b'), ObjectId('69c421dd055b4a41fe853b3c'), ObjectId('69c421dd055b4a41fe853b3d'), ObjectId('69c421dd055b4a41fe853b3e'), ObjectId('69c421dd055b4a41fe853b3f'), ObjectId('69c421dd055b4a41fe853b40'), ObjectId('69c421dd055b4a41fe853b41'), ObjectId('69c421dd055b4a41fe853b42'), ObjectId('69c421dd055b4a41fe853b43'), ObjectId('69c421dd055b4a41fe853b44'), ObjectId('69c421dd055b4a41fe853b45'), ObjectId('69c421dd055b4a41fe853b46'), ObjectId('69c421dd055b4a41fe853b47'), ObjectId('69c421dd055b4a41fe853b48'), ObjectId('69c421dd055b4a41fe853b49'), ObjectId('69c421dd055b4a41fe853b4a'), ObjectId('69c421dd055b4a41fe853b4b'), ObjectId('69c421dd055b4a41fe853b4c'), ObjectId('69c421dd055b4a41fe853b4d'), ObjectId('69c421dd055b4a41fe853b4e'), ObjectId('69c421dd055b4a41fe853b4f'), ObjectId('69c421dd055b4a41fe853b50'), ObjectId('69c421dd055b4a41fe853b51'), ObjectId('69c421dd055b4a41fe853b52'), ObjectId('69c421dd055b4a41fe853b53'), ObjectId('69c421dd055b4a41fe853b54'), ObjectId('69c421dd055b4a41fe853b55'), ObjectId('69c421dd055b4a41fe853b56'), ObjectId('69c421dd055b4a41fe853b57'), ObjectId('69c421dd055b4a41fe853b58'), ObjectId('69c421dd055b4a41fe853b59'), ObjectId('69c421dd055b4a41fe853b5a'), ObjectId('69c421dd055b4a41fe853b5b'), ObjectId('69c421dd055b4a41fe853b5c'), ObjectId('69c421dd055b4a41fe853b5d'), ObjectId('69c421dd055b4a41fe853b5e')], acknowledged=True)

In [176]:
dados_mongo = list(colecao.find({
    'valor' : {'$gte': 90, '$lte': 200}
}))

display(dados_mongo)

[{'_id': ObjectId('69c33af50cba3aca31ef8c59'),
  'tutor': 'Ana',
  'animal': 'Cachorro',
  'nome_pet': 'Rex1',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c5a'),
  'tutor': 'Bruno',
  'animal': 'Gato',
  'nome_pet': 'Mimi2',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c5c'),
  'tutor': 'Daniela',
  'animal': 'Ave',
  'nome_pet': 'Piu4',
  'servico': 'Exame',
  'valor': 180,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c5d'),
  'tutor': 'Eduardo',
  'animal': 'Gato',
  'nome_pet': 'Luna5',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c5e'),
  'tutor': 'Fernanda',
  'animal': 'Cachorro',
  'nome_pet': 'Bob6',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c5f'),
  'tutor': 'Gabriel',
  'animal': 'Coelho',
  'nome_pet': 'Pompom7',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c62'),
  'tutor': 'Juliana',
  'animal': 'Cachorro',
  'nome_pet': 'Nina10',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c63'),
  'tutor': 'Lucas',
  'animal': 'Ave',
  'nome_pet': 'Sky11',
  'servico': 'Exame',
  'valor': 200,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c64'),
  'tutor': 'Mariana',
  'animal': 'Gato',
  'nome_pet': 'Lili12',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c65'),
  'tutor': 'Nicolas',
  'animal': 'Cachorro',
  'nome_pet': 'Bolt13',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c66'),
  'tutor': 'Patricia',
  'animal': 'Cachorro',
  'nome_pet': 'Max14',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c69'),
  'tutor': 'Thiago',
  'animal': 'Ave',
  'nome_pet': 'Blue17',
  'servico': 'Exame',
  'valor': 170,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c6a'),
  'tutor': 'Vanessa',
  'animal': 'Gato',
  'nome_pet': 'Nino18',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c6b'),
  'tutor': 'William',
  'animal': 'Cachorro',
  'nome_pet': 'Thor19',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c6c'),
  'tutor': 'Beatriz',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy20',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c6e'),
  'tutor': 'Diego',
  'animal': 'Gato',
  'nome_pet': 'Tom22',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c70'),
  'tutor': 'Felipe',
  'animal': 'Ave',
  'nome_pet': 'Kiwi24',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c72'),
  'tutor': 'Hugo',
  'animal': 'Cachorro',
  'nome_pet': 'Rex26',
  'servico': 'Consulta',
  'valor': 150,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c73'),
  'tutor': 'Iris',
  'animal': 'Cachorro',
  'nome_pet': 'Bob27',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c76'),
  'tutor': 'Leo',
  'animal': 'Ave',
  'nome_pet': 'Sky30',
  'servico': 'Exame',
  'valor': 160,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c77'),
  'tutor': 'Marta',
  'animal': 'Gato',
  'nome_pet': 'Mimi31',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c78'),
  'tutor': 'Nelson',
  'animal': 'Cachorro',
  'nome_pet': 'Max32',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c79'),
  'tutor': 'Olga',
  'animal': 'Coelho',
  'nome_pet': 'Pompom33',
  'servico': 'Consulta',
  'valor': 105,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c7b'),
  'tutor': 'Quezia',
  'animal': 'Gato',
  'nome_pet': 'Simba35',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c7c'),
  'tutor': 'Renato',
  'animal': 'Cachorro',
  'nome_pet': 'Nina36',
  'servico': 'Exame',
  'valor': 190,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c7d'),
  'tutor': 'Sara',
  'animal': 'Ave',
  'nome_pet': 'Blue37',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c7f'),
  'tutor': 'Ursula',
  'animal': 'Cachorro',
  'nome_pet': 'Rex39',
  'servico': 'Consulta',
  'valor': 145,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c82'),
  'tutor': 'Xuxa',
  'animal': 'Ave',
  'nome_pet': 'Piu42',
  'servico': 'Exame',
  'valor': 175,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c83'),
  'tutor': 'Yara',
  'animal': 'Gato',
  'nome_pet': 'Luna43',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c84'),
  'tutor': 'Zeca',
  'animal': 'Cachorro',
  'nome_pet': 'Bob44',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c85'),
  'tutor': 'Aline',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy45',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c87'),
  'tutor': 'Cesar',
  'animal': 'Gato',
  'nome_pet': 'Tom47',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c89'),
  'tutor': 'Enzo',
  'animal': 'Ave',
  'nome_pet': 'Kiwi49',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c8a'),
  'tutor': 'Fabio',
  'animal': 'Gato',
  'nome_pet': 'Nina50',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3eb8943558b98f303e291'),
  'tutor': 'Ana',
  'animal': 'Cachorro',
  'nome_pet': 'Rex1',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e292'),
  'tutor': 'Bruno',
  'animal': 'Gato',
  'nome_pet': 'Mimi2',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3eb8943558b98f303e294'),
  'tutor': 'Daniela',
  'animal': 'Ave',
  'nome_pet': 'Piu4',
  'servico': 'Exame',
  'valor': 180,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3eb8943558b98f303e295'),
  'tutor': 'Eduardo',
  'animal': 'Gato',
  'nome_pet': 'Luna5',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e296'),
  'tutor': 'Fernanda',
  'animal': 'Cachorro',
  'nome_pet': 'Bob6',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3eb8943558b98f303e297'),
  'tutor': 'Gabriel',
  'animal': 'Coelho',
  'nome_pet': 'Pompom7',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e29a'),
  'tutor': 'Juliana',
  'animal': 'Cachorro',
  'nome_pet': 'Nina10',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e29b'),
  'tutor': 'Lucas',
  'animal': 'Ave',
  'nome_pet': 'Sky11',
  'servico': 'Exame',
  'valor': 200,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3eb8943558b98f303e29c'),
  'tutor': 'Mariana',
  'animal': 'Gato',
  'nome_pet': 'Lili12',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e29d'),
  'tutor': 'Nicolas',
  'animal': 'Cachorro',
  'nome_pet': 'Bolt13',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3eb8943558b98f303e29e'),
  'tutor': 'Patricia',
  'animal': 'Cachorro',
  'nome_pet': 'Max14',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2a1'),
  'tutor': 'Thiago',
  'animal': 'Ave',
  'nome_pet': 'Blue17',
  'servico': 'Exame',
  'valor': 170,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2a2'),
  'tutor': 'Vanessa',
  'animal': 'Gato',
  'nome_pet': 'Nino18',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3eb8943558b98f303e2a3'),
  'tutor': 'William',
  'animal': 'Cachorro',
  'nome_pet': 'Thor19',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2a4'),
  'tutor': 'Beatriz',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy20',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3eb8943558b98f303e2a6'),
  'tutor': 'Diego',
  'animal': 'Gato',
  'nome_pet': 'Tom22',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2a8'),
  'tutor': 'Felipe',
  'animal': 'Ave',
  'nome_pet': 'Kiwi24',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2aa'),
  'tutor': 'Hugo',
  'animal': 'Cachorro',
  'nome_pet': 'Rex26',
  'servico': 'Consulta',
  'valor': 150,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3eb8943558b98f303e2ab'),
  'tutor': 'Iris',
  'animal': 'Cachorro',
  'nome_pet': 'Bob27',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2ae'),
  'tutor': 'Leo',
  'animal': 'Ave',
  'nome_pet': 'Sky30',
  'servico': 'Exame',
  'valor': 160,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2af'),
  'tutor': 'Marta',
  'animal': 'Gato',
  'nome_pet': 'Mimi31',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3eb8943558b98f303e2b0'),
  'tutor': 'Nelson',
  'animal': 'Cachorro',
  'nome_pet': 'Max32',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2b1'),
  'tutor': 'Olga',
  'animal': 'Coelho',
  'nome_pet': 'Pompom33',
  'servico': 'Consulta',
  'valor': 105,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3eb8943558b98f303e2b3'),
  'tutor': 'Quezia',
  'animal': 'Gato',
  'nome_pet': 'Simba35',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2b4'),
  'tutor': 'Renato',
  'animal': 'Cachorro',
  'nome_pet': 'Nina36',
  'servico': 'Exame',
  'valor': 190,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3eb8943558b98f303e2b5'),
  'tutor': 'Sara',
  'animal': 'Ave',
  'nome_pet': 'Blue37',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2b7'),
  'tutor': 'Ursula',
  'animal': 'Cachorro',
  'nome_pet': 'Rex39',
  'servico': 'Consulta',
  'valor': 145,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2ba'),
  'tutor': 'Xuxa',
  'animal': 'Ave',
  'nome_pet': 'Piu42',
  'servico': 'Exame',
  'valor': 175,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2bb'),
  'tutor': 'Yara',
  'animal': 'Gato',
  'nome_pet': 'Luna43',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3eb8943558b98f303e2bc'),
  'tutor': 'Zeca',
  'animal': 'Cachorro',
  'nome_pet': 'Bob44',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2bd'),
  'tutor': 'Aline',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy45',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3eb8943558b98f303e2bf'),
  'tutor': 'Cesar',
  'animal': 'Gato',
  'nome_pet': 'Tom47',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2c1'),
  'tutor': 'Enzo',
  'animal': 'Ave',
  'nome_pet': 'Kiwi49',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2c2'),
  'tutor': 'Fabio',
  'animal': 'Gato',
  'nome_pet': 'Nina50',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3ee1743558b98f303e2c4'),
  'tutor': 'Ana',
  'animal': 'Cachorro',
  'nome_pet': 'Rex1',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3ee1743558b98f303e2c5'),
  'tutor': 'Bruno',
  'animal': 'Gato',
  'nome_pet': 'Mimi2',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3ee1743558b98f303e2c7'),
  'tutor': 'Daniela',
  'animal': 'Ave',
  'nome_pet': 'Piu4',
  'servico': 'Exame',
  'valor': 180,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3ee1743558b98f303e2c8'),
  'tutor': 'Eduardo',
  'animal': 'Gato',
  'nome_pet': 'Luna5',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3ee1743558b98f303e2c9'),
  'tutor': 'Fernanda',
  'animal': 'Cachorro',
  'nome_pet': 'Bob6',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3ee1743558b98f303e2ca'),
  'tutor': 'Gabriel',
  'animal': 'Coelho',
  'nome_pet': 'Pompom7',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3ee1743558b98f303e2cd'),
  'tutor': 'Juliana',
  'animal': 'Cachorro',
  'nome_pet': 'Nina10',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3ee1743558b98f303e2ce'),
  'tutor': 'Lucas',
  'animal': 'Ave',
  'nome_pet': 'Sky11',
  'servico': 'Exame',
  'valor': 200,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3ee1743558b98f303e2cf'),
  'tutor': 'Mariana',
  'animal': 'Gato',
  'nome_pet': 'Lili12',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3ee1743558b98f303e2d0'),
  'tutor': 'Nicolas',
  'animal': 'Cachorro',
  'nome_pet': 'Bolt13',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3ee1743558b98f303e2d1'),
  'tutor': 'Patricia',
  'animal': 'Cachorro',
  'nome_pet': 'Max14',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Ourinhos',

In [177]:
dados_cidade = list(colecao.find({
    'cidade' : {'$in' : ['Assis', 'Ourinhos', 'Pompeia', 'Marilia']}
}))

display(dados_cidade)

[{'_id': ObjectId('69c33af50cba3aca31ef8c59'),
  'tutor': 'Ana',
  'animal': 'Cachorro',
  'nome_pet': 'Rex1',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c5a'),
  'tutor': 'Bruno',
  'animal': 'Gato',
  'nome_pet': 'Mimi2',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c5b'),
  'tutor': 'Carlos',
  'animal': 'Cachorro',
  'nome_pet': 'Thor3',
  'servico': 'Banho',
  'valor': 60,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c5c'),
  'tutor': 'Daniela',
  'animal': 'Ave',
  'nome_pet': 'Piu4',
  'servico': 'Exame',
  'valor': 180,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c5d'),
  'tutor': 'Eduardo',
  'animal': 'Gato',
  'nome_pet': 'Luna5',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c5e'),
  'tutor': 'Fernanda',
  'animal': 'Cachorro',
  'nome_pet': 'Bob6',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c5f'),
  'tutor': 'Gabriel',
  'animal': 'Coelho',
  'nome_pet': 'Pompom7',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c60'),
  'tutor': 'Helena',
  'animal': 'Cachorro',
  'nome_pet': 'Mel8',
  'servico': 'Cirurgia',
  'valor': 820,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c61'),
  'tutor': 'Igor',
  'animal': 'Gato',
  'nome_pet': 'Simba9',
  'servico': 'Banho',
  'valor': 55,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c62'),
  'tutor': 'Juliana',
  'animal': 'Cachorro',
  'nome_pet': 'Nina10',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c63'),
  'tutor': 'Lucas',
  'animal': 'Ave',
  'nome_pet': 'Sky11',
  'servico': 'Exame',
  'valor': 200,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c64'),
  'tutor': 'Mariana',
  'animal': 'Gato',
  'nome_pet': 'Lili12',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c65'),
  'tutor': 'Nicolas',
  'animal': 'Cachorro',
  'nome_pet': 'Bolt13',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c66'),
  'tutor': 'Patricia',
  'animal': 'Cachorro',
  'nome_pet': 'Max14',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c67'),
  'tutor': 'Rafael',
  'animal': 'Gato',
  'nome_pet': 'Mia15',
  'servico': 'Banho',
  'valor': 65,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c68'),
  'tutor': 'Sofia',
  'animal': 'Cachorro',
  'nome_pet': 'Luna16',
  'servico': 'Cirurgia',
  'valor': 900,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c69'),
  'tutor': 'Thiago',
  'animal': 'Ave',
  'nome_pet': 'Blue17',
  'servico': 'Exame',
  'valor': 170,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c6a'),
  'tutor': 'Vanessa',
  'animal': 'Gato',
  'nome_pet': 'Nino18',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c6b'),
  'tutor': 'William',
  'animal': 'Cachorro',
  'nome_pet': 'Thor19',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c6c'),
  'tutor': 'Beatriz',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy20',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c6d'),
  'tutor': 'Caio',
  'animal': 'Cachorro',
  'nome_pet': 'Spike21',
  'servico': 'Banho',
  'valor': 70,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c6e'),
  'tutor': 'Diego',
  'animal': 'Gato',
  'nome_pet': 'Tom22',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c6f'),
  'tutor': 'Elisa',
  'animal': 'Cachorro',
  'nome_pet': 'Mel23',
  'servico': 'Exame',
  'valor': 210,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c70'),
  'tutor': 'Felipe',
  'animal': 'Ave',
  'nome_pet': 'Kiwi24',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c71'),
  'tutor': 'Gisele',
  'animal': 'Gato',
  'nome_pet': 'Nina25',
  'servico': 'Vacinação',
  'valor': 85,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c72'),
  'tutor': 'Hugo',
  'animal': 'Cachorro',
  'nome_pet': 'Rex26',
  'servico': 'Consulta',
  'valor': 150,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c73'),
  'tutor': 'Iris',
  'animal': 'Cachorro',
  'nome_pet': 'Bob27',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c74'),
  'tutor': 'Joao',
  'animal': 'Gato',
  'nome_pet': 'Luna28',
  'servico': 'Banho',
  'valor': 60,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c75'),
  'tutor': 'Karen',
  'animal': 'Cachorro',
  'nome_pet': 'Thor29',
  'servico': 'Cirurgia',
  'valor': 780,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c76'),
  'tutor': 'Leo',
  'animal': 'Ave',
  'nome_pet': 'Sky30',
  'servico': 'Exame',
  'valor': 160,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c77'),
  'tutor': 'Marta',
  'animal': 'Gato',
  'nome_pet': 'Mimi31',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c78'),
  'tutor': 'Nelson',
  'animal': 'Cachorro',
  'nome_pet': 'Max32',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c79'),
  'tutor': 'Olga',
  'animal': 'Coelho',
  'nome_pet': 'Pompom33',
  'servico': 'Consulta',
  'valor': 105,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c7a'),
  'tutor': 'Paulo',
  'animal': 'Cachorro',
  'nome_pet': 'Bolt34',
  'servico': 'Banho',
  'valor': 75,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c7b'),
  'tutor': 'Quezia',
  'animal': 'Gato',
  'nome_pet': 'Simba35',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c7c'),
  'tutor': 'Renato',
  'animal': 'Cachorro',
  'nome_pet': 'Nina36',
  'servico': 'Exame',
  'valor': 190,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c7d'),
  'tutor': 'Sara',
  'animal': 'Ave',
  'nome_pet': 'Blue37',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c7e'),
  'tutor': 'Tiago',
  'animal': 'Gato',
  'nome_pet': 'Lili38',
  'servico': 'Vacinação',
  'valor': 85,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c7f'),
  'tutor': 'Ursula',
  'animal': 'Cachorro',
  'nome_pet': 'Rex39',
  'servico': 'Consulta',
  'valor': 145,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c80'),
  'tutor': 'Vitor',
  'animal': 'Gato',
  'nome_pet': 'Mia40',
  'servico': 'Banho',
  'valor': 70,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c81'),
  'tutor': 'Wesley',
  'animal': 'Cachorro',
  'nome_pet': 'Thor41',
  'servico': 'Cirurgia',
  'valor': 870,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c82'),
  'tutor': 'Xuxa',
  'animal': 'Ave',
  'nome_pet': 'Piu42',
  'servico': 'Exame',
  'valor': 175,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c83'),
  'tutor': 'Yara',
  'animal': 'Gato',
  'nome_pet': 'Luna43',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c84'),
  'tutor': 'Zeca',
  'animal': 'Cachorro',
  'nome_pet': 'Bob44',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c85'),
  'tutor': 'Aline',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy45',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c86'),
  'tutor': 'Bruna',
  'animal': 'Cachorro',
  'nome_pet': 'Spike46',
  'servico': 'Banho',
  'valor': 80,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c87'),
  'tutor': 'Cesar',
  'animal': 'Gato',
  'nome_pet': 'Tom47',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c88'),
  'tutor': 'Dora',
  'animal': 'Cachorro',
  'nome_pet': 'Mel48',
  'servico': 'Exame',
  'valor': 220,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c89'),
  'tutor': 'Enzo',
  'animal': 'Ave',
  'nome_pet': 'Kiwi49',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c33af50cba3aca31ef8c8a'),
  'tutor': 'Fabio',
  'animal': 'Gato',
  'nome_pet': 'Nina50',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3eb8943558b98f303e291'),
  'tutor': 'Ana',
  'animal': 'Cachorro',
  'nome_pet': 'Rex1',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e292'),
  'tutor': 'Bruno',
  'animal': 'Gato',
  'nome_pet': 'Mimi2',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3eb8943558b98f303e293'),
  'tutor': 'Carlos',
  'animal': 'Cachorro',
  'nome_pet': 'Thor3',
  'servico': 'Banho',
  'valor': 60,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3eb8943558b98f303e294'),
  'tutor': 'Daniela',
  'animal': 'Ave',
  'nome_pet': 'Piu4',
  'servico': 'Exame',
  'valor': 180,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3eb8943558b98f303e295'),
  'tutor': 'Eduardo',
  'animal': 'Gato',
  'nome_pet': 'Luna5',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e296'),
  'tutor': 'Fernanda',
  'animal': 'Cachorro',
  'nome_pet': 'Bob6',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3eb8943558b98f303e297'),
  'tutor': 'Gabriel',
  'animal': 'Coelho',
  'nome_pet': 'Pompom7',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e298'),
  'tutor': 'Helena',
  'animal': 'Cachorro',
  'nome_pet': 'Mel8',
  'servico': 'Cirurgia',
  'valor': 820,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3eb8943558b98f303e299'),
  'tutor': 'Igor',
  'animal': 'Gato',
  'nome_pet': 'Simba9',
  'servico': 'Banho',
  'valor': 55,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3eb8943558b98f303e29a'),
  'tutor': 'Juliana',
  'animal': 'Cachorro',
  'nome_pet': 'Nina10',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e29b'),
  'tutor': 'Lucas',
  'animal': 'Ave',
  'nome_pet': 'Sky11',
  'servico': 'Exame',
  'valor': 200,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3eb8943558b98f303e29c'),
  'tutor': 'Mariana',
  'animal': 'Gato',
  'nome_pet': 'Lili12',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e29d'),
  'tutor': 'Nicolas',
  'animal': 'Cachorro',
  'nome_pet': 'Bolt13',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3eb8943558b98f303e29e'),
  'tutor': 'Patricia',
  'animal': 'Cachorro',
  'nome_pet': 'Max14',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e29f'),
  'tutor': 'Rafael',
  'animal': 'Gato',
  'nome_pet': 'Mia15',
  'servico': 'Banho',
  'valor': 65,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3eb8943558b98f303e2a0'),
  'tutor': 'Sofia',
  'animal': 'Cachorro',
  'nome_pet': 'Luna16',
  'servico': 'Cirurgia',
  'valor': 900,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3eb8943558b98f303e2a1'),
  'tutor': 'Thiago',
  'animal': 'Ave',
  'nome_pet': 'Blue17',
  'servico': 'Exame',
  'valor': 170,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2a2'),
  'tutor': 'Vanessa',
  'animal': 'Gato',
  'nome_pet': 'Nino18',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3eb8943558b98f303e2a3'),
  'tutor': 'William',
  'animal': 'Cachorro',
  'nome_pet': 'Thor19',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2a4'),
  'tutor': 'Beatriz',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy20',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3eb8943558b98f303e2a5'),
  'tutor': 'Caio',
  'animal': 'Cachorro',
  'nome_pet': 'Spike21',
  'servico': 'Banho',
  'valor': 70,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3eb8943558b98f303e2a6'),
  'tutor': 'Diego',
  'animal': 'Gato',
  'nome_pet': 'Tom22',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2a7'),
  'tutor': 'Elisa',
  'animal': 'Cachorro',
  'nome_pet': 'Mel23',
  'servico': 'Exame',
  'valor': 210,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3eb8943558b98f303e2a8'),
  'tutor': 'Felipe',
  'animal': 'Ave',
  'nome_pet': 'Kiwi24',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2a9'),
  'tutor': 'Gisele',
  'animal': 'Gato',
  'nome_pet': 'Nina25',
  'servico': 'Vacinação',
  'valor': 85,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3eb8943558b98f303e2aa'),
  'tutor': 'Hugo',
  'animal': 'Cachorro',
  'nome_pet': 'Rex26',
  'servico': 'Consulta',
  'valor': 150,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3eb8943558b98f303e2ab'),
  'tutor': 'Iris',
  'animal': 'Cachorro',
  'nome_pet': 'Bob27',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3eb8943558b98f303e2ac'),
  'tutor': 'Joao',
  'animal': 'Gato',
  'nome_pet': 'Luna28',
  'servico': 'Banho',
  'valor': 60,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3eb8943558b98f303e2ad'),
  'tutor': 'Karen',
  'animal': 'Cachorro',
  'nome_pet': 'Thor29',
  'servico': 'Cirurgia',
  'valor': 780,
  'cidade': 'Pompeia',

In [178]:
df = pd.DataFrame(dados_cidade)
df

,_id,tutor,animal,nome_pet,servico,valor,cidade,data,forma_pagamento
0,69c33af50cba3aca31ef8c59,Ana,Cachorro,Rex1,Consulta,120,Assis,2026-03-01,Pix
1,69c33af50cba3aca31ef8c5a,Bruno,Gato,Mimi2,Vacinação,95,Assis,2026-03-02,Cartão
2,69c33af50cba3aca31ef8c5b,Carlos,Cachorro,Thor3,Banho,60,Assis,2026-03-03,Dinheiro
3,69c33af50cba3aca31ef8c5c,Daniela,Ave,Piu4,Exame,180,Assis,2026-03-04,Cartão
4,69c33af50cba3aca31ef8c5d,Eduardo,Gato,Luna5,Consulta,130,Assis,2026-03-05,Pix
...,...,...,...,...,...,...,...,...,...
395,69c421dd055b4a41fe853b5a,Bruna,Cachorro,Spike46,Banho,80,Marilia,2026-03-08,Dinheiro
396,69c421dd055b4a41fe853b5b,Cesar,Gato,Tom47,Consulta,140,Marilia,2026-03-09,Pix
397,69c421dd055b4a41fe853b5c,Dora,Cachorro,Mel48,Exame,220,Marilia,2026-03-10,Cartão
398,69c421dd055b4a41fe853b5d,Enzo,Ave,Kiwi49,Consulta,130,Marilia,2026-03-11,Pix
399,69c421dd055b4a41fe853b5e,Fabio,Gato,Nina50,Vacinação,90,Marilia,2026-03-12,Dinheiro

In [179]:
df.isnull().sum()

_id                0
tutor              0
animal             0
nome_pet           0
servico            0
valor              0
cidade             0
data               0
forma_pagamento    0
dtype: int64

In [180]:
df['valor_total'] = df['valor'].sum()
df.head(3)

,_id,tutor,animal,nome_pet,servico,valor,cidade,data,forma_pagamento,valor_total
0,69c33af50cba3aca31ef8c59,Ana,Cachorro,Rex1,Consulta,120,Assis,2026-03-01,Pix,71160
1,69c33af50cba3aca31ef8c5a,Bruno,Gato,Mimi2,Vacinação,95,Assis,2026-03-02,Cartão,71160
2,69c33af50cba3aca31ef8c5b,Carlos,Cachorro,Thor3,Banho,60,Assis,2026-03-03,Dinheiro,71160

In [181]:
faturamento = df['valor_total'].sum()
print("Faturamento total: ", faturamento)

Faturamento total:  28464000

In [182]:
faturamento_cidade = df.groupby('cidade')['valor'].sum().sort_values(ascending=False)
faturamento_cidade

cidade
Ourinhos    19040
Marilia     18200
Assis       17760
Pompeia     16160
Name: valor, dtype: int64

In [183]:
faturamento_servico = df.groupby('servico')['valor'].sum().sort_values(ascending=False)
faturamento_servico

servico
Cirurgia     26960
Consulta     21240
Exame        12040
Vacinação     6640
Banho         4280
Name: valor, dtype: int64

In [184]:
vendas_cidade = df['cidade'].value_counts()
vendas_cidade

cidade
Assis       104
Ourinhos    104
Pompeia      96
Marilia      96
Name: count, dtype: int64

In [185]:
ticket_medio = df['valor'].mean()
print(f"Media do valor das vendas: {ticket_medio:.2f}")

Media do valor das vendas: 177.90

In [186]:
ticket_medio_cidade = df.groupby('cidade')['valor'].mean().sort_values(ascending=False)
ticket_medio_cidade

cidade
Marilia     189.583333
Ourinhos    183.076923
Assis       170.769231
Pompeia     168.333333
Name: valor, dtype: float64

In [187]:
servico_top = df.groupby('servico') ['valor_total'].sum().idxmax()
servico_top

'Consulta'

In [188]:
cidade_top = df['cidade'].value_counts() .idxmax()
cidade_top

'Assis'

In [198]:
maioresAtendimentos = df.groupby('servico') ['valor_total'].sum().sort_values(ascending=False)
maioresAtendimentos

servico
Consulta     11954880
Vacinação     5123520
Banho         4554240
Exame         4554240
Cirurgia      2277120
Name: valor_total, dtype: int64

In [195]:
relatorioPetShop = {
    'data_geracao': datetime.now(),
    'faturamento_total': float(faturamento), 
    'faturamento_cidade': faturamento_cidade.to_dict(),
    'faturamento_servico': faturamento_servico.to_dict(),
    'ticket_medio_geral': float(ticket_medio),
    'ticket_medio_por_cidade': ticket_medio_cidade.to_dict(),
    'ticket_mais_lucrativo': servico_top,
    'cidade_maior_faturamento': cidade_top,
    'top_3_atendimentos': maioresAtendimentos
    
}

display(relatorioPetShop)

{'data_geracao': datetime.datetime(2026, 3, 25, 18, 0, 5, 704138),
 'faturamento_total': 28464000.0,
 'faturamento_cidade': {'Ourinhos': 19040,
  'Marilia': 18200,
  'Assis': 17760,
  'Pompeia': 16160},
 'faturamento_servico': {'Cirurgia': 26960,
  'Consulta': 21240,
  'Exame': 12040,
  'Vacinação': 6640,
  'Banho': 4280},
 'ticket_medio_geral': 177.9,
 'ticket_medio_por_cidade': {'Marilia': 189.58333333333334,
  'Ourinhos': 183.07692307692307,
  'Assis': 170.76923076923077,
  'Pompeia': 168.33333333333334},
 'ticket_mais_lucrativo': 'Consulta',
 'cidade_maior_faturamento': 'Assis',
 'top_3_atendimentos': servico
 Consulta     11954880
 Vacinação     5123520
 Banho         4554240
 Exame         4554240
 Cirurgia      2277120
 Name: valor_total, dtype: int64}

In [191]:
colecao_relatorios = db['relatorio']
colecao_relatorios.insert_one(relatorioPetShop)

InvalidDocument: Invalid document: cannot encode object: servico
Consulta     11954880
Vacinação     5123520
Banho         4554240
Exame         4554240
Cirurgia      2277120
Name: valor_total, dtype: int64, of type: <class 'pandas.Series'>

In [196]:
for r in colecao_relatorios.find():
    display(r)

{'_id': ObjectId('69c41e41055b4a41fe853b2a'),
 'data_geracao': datetime.datetime(2026, 3, 25, 17, 41, 18, 497000),
 'faturamento_total': 21792750.0,
 'faturamento_cidade': {'Ourinhos': 16660,
  'Marilia': 15925,
  'Assis': 15540,
  'Pompeia': 14140},
 'faturamento_servico': {'Cirurgia': 23590,
  'Consulta': 18585,
  'Exame': 10535,
  'Vacinação': 5810,
  'Banho': 3745},
 'ticket_medio_geral': 177.9,
 'ticket_medio_por_cidade': {'Marilia': 189.58333333333334,
  'Ourinhos': 183.07692307692307,
  'Assis': 170.76923076923077,
  'Pompeia': 168.33333333333334},
 'ticket_mais_lucrativo': 'Consulta',
 'cidade_maior_faturamento': 'Assis'}